import csv
import json
import os


CSV_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data", "Spotify_Song_Attributes.csv")

GENRE_COLORS = {
    # Pop
    "pop": "#1f6fca",
    "dance pop": "#be185d",
    "indie pop": "#7c3aed",
    "art pop": "#0e7490",
    "chill pop": "#15803d",
    "bedroom pop": "#d97706",
    "baroque pop": "#9d174d",
    "dark pop": "#4c1d95",
    "experimental pop": "#7e22ce",
    "shimmer pop": "#a78bfa",
    "antiviral pop": "#8b5cf6",
    "gauze pop": "#c084fc",
    "vapor pop": "#818cf8",
    "channel pop": "#3b82f6",
    "modern indie pop": "#8b5cf6",
    "melodipop": "#4f46e5",
    "noise pop": "#dc2626",
    "industrial pop": "#374151",
    "social media pop": "#818cf8",
    "viral pop": "#6366f1",
    "ambient pop": "#0f766e",
    "chamber pop": "#92400e",
    "hypnagogic pop": "#7c3aed",
    "neo mellow": "#b45309",
    "candy pop": "#ec4899",
    "boy pop": "#60a5fa",
    "teen pop": "#f472b6",
    "post-teen pop": "#c084fc",
    "bubblegum dance": "#f472b6",
    "europop": "#1d4ed8",
    "electropop": "#0891b2",
    "hyperpop": "#a855f7",
    "la pop": "#1e40af",
    "nyc pop": "#1f6fca",
    "singer-songwriter pop": "#b45309",
    "alt z": "#9333ea",
    "acoustic pop": "#0e7490",
    "australian pop": "#1f6fca",
    "canadian pop": "#1f6fca",
    "colombian pop": "#1f6fca",
    "danish pop": "#1f6fca",
    "dutch pop": "#1f6fca",
    "german pop": "#1f6fca",
    "irish pop": "#15803d",
    "israeli pop": "#1f6fca",
    "kazakh pop": "#1f6fca",
    "malaysian pop": "#1f6fca",
    "norwegian pop": "#1f6fca",
    "nz pop": "#1f6fca",
    "romanian pop": "#1f6fca",
    "russian pop": "#1f6fca",
    "scandipop": "#1f6fca",
    "singaporean pop": "#1f6fca",
    "south african pop": "#d97706",
    "swedish pop": "#1f6fca",
    "swiss pop": "#1f6fca",
    "uk pop": "#1f6fca",
    "ukrainian viral pop": "#1f6fca",
    "barbadian pop": "#1f6fca",
    "desi pop": "#b45309",
    "afghan pop": "#b45309",
    "assamese pop": "#b45309",
    "bhojpuri pop": "#b45309",
    "gujarati pop": "#b45309",
    "hindi indie": "#b45309",
    "himachali pop": "#b45309",
    "hmong pop": "#b45309",
    "indonesian singer-songwriter": "#b45309",
    "odia pop": "#b45309",
    "pakistani pop": "#b45309",
    "persian pop": "#b45309",
    "punjabi pop": "#d97706",
    "singaporean singer-songwriter": "#b45309",
    "telugu indie": "#b45309",
    "pop dance": "#be185d",
    "pop edm": "#0d9488",
    "pop folk": "#92400e",
    "pop r&b": "#0d9488",
    "pop rap": "#6d28d9",
    "pop soul": "#b45309",
    "pop quebecois": "#1f6fca",
    "french pop": "#db2777",
    "french indie pop": "#db2777",
    "electro-pop francais": "#db2777",
    "antiviral pop": "#8b5cf6",
    "chinese idol pop": "#e11d48",
    "chinese viral pop": "#db2777",
    "chinese electropop": "#db2777",
    "classic uk pop": "#1f6fca",
    "classic swedish pop": "#1f6fca",
    "new wave pop": "#0891b2",
    "new romantic": "#db2777",
    "bow pop": "#1f6fca",
    "metropopolis": "#1f6fca",
    "hip pop": "#6d28d9",
    # Rock
    "classic rock": "#b91c1c",
    "modern rock": "#2563eb",
    "indie rock": "#d946ef",
    "alternative rock": "#7c3aed",
    "alternative metal": "#d97706",
    "modern alternative rock": "#dc2626",
    "modern alternative pop": "#7c3aed",
    "hard rock": "#ef4444",
    "grunge": "#78350f",
    "post-grunge": "#78350f",
    "garage rock": "#ea580c",
    "garage rock revival": "#f97316",
    "glam rock": "#db2777",
    "glam metal": "#ec4899",
    "sleaze rock": "#9a3412",
    "album rock": "#991b1b",
    "dance rock": "#dc2626",
    "alternative pop rock": "#dc2626",
    "indie garage rock": "#ea580c",
    "indie rockism": "#d946ef",
    "indie rock italiano": "#dc2626",
    "british alternative rock": "#7c3aed",
    "british indie rock": "#d946ef",
    "english indie rock": "#d946ef",
    "australian alternative rock": "#dc2626",
    "australian rock": "#dc2626",
    "austin rock": "#dc2626",
    "blues rock": "#b91c1c",
    "celtic rock": "#15803d",
    "christian alternative rock": "#1e40af",
    "christian rock": "#1e40af",
    "death metal": "#7f1d1d",
    "metallic hardcore": "#7f1d1d",
    "alternative metal": "#d97706",
    "funk metal": "#b91c1c",
    "melodic metalcore": "#b91c1c",
    "freeform hardcore": "#b91c1c",
    "future rock": "#dc2626",
    "piano rock": "#dc2626",
    "rap rock": "#dc2626",
    "german pop rock": "#dc2626",
    "glitch": "#4c1d95",
    "noise pop": "#dc2626",
    "permanent wave": "#dc2626",
    "indie anthem-folk": "#92400e",
    "indie emo": "#7c3aed",
    "emo": "#7c3aed",
    "emo rap": "#6d28d9",
    "dreamo": "#7c3aed",
    "neon pop punk": "#ec4899",
    "sped up": "#dc2626",
    "super eurobeat": "#dc2626",
    "eurobeat": "#dc2626",
    "brostep": "#b91c1c",
    "j-rock": "#dc2626",
    "j-poprock": "#dc2626",
    "japanese alternative rock": "#dc2626",
    "anime rock": "#dc2626",
    "finnish alternative rock": "#dc2626",
    "thai indie rock": "#dc2626",
    "irish rock": "#15803d",
    "scottish indie": "#15803d",
    "piano rock": "#dc2626",
    "instrumental math rock": "#d97706",
    "instrumental post-rock": "#64748b",
    # Hip-Hop / Rap
    "hip hop": "#7c3aed",
    "cloud rap": "#6d28d9",
    "trap": "#4c1d95",
    "gangster rap": "#4c1d95",
    "conscious hip hop": "#6d28d9",
    "east coast hip hop": "#6d28d9",
    "atl hip hop": "#6d28d9",
    "cali rap": "#6d28d9",
    "memphis hip hop": "#4c1d95",
    "detroit hip hop": "#6d28d9",
    "chicago rap": "#6d28d9",
    "dmv rap": "#6d28d9",
    "dfw rap": "#6d28d9",
    "nyc rap": "#6d28d9",
    "alabama rap": "#6d28d9",
    "ohio hip hop": "#6d28d9",
    "pittsburgh rap": "#6d28d9",
    "florida drill": "#4c1d95",
    "brooklyn drill": "#4c1d95",
    "melodic drill": "#4c1d95",
    "dark trap": "#4c1d95",
    "dark plugg": "#4c1d95",
    "plugg": "#4c1d95",
    "pluggnb": "#4c1d95",
    "bass trap": "#4c1d95",
    "rage rap": "#b91c1c",
    "sad rap": "#4c1d95",
    "melodic rap": "#6d28d9",
    "aesthetic rap": "#8b5cf6",
    "indie pop rap": "#8b5cf6",
    "trap queen": "#ec4899",
    "traprun": "#4c1d95",
    "nightrun": "#4c1d95",
    "viral rap": "#6d28d9",
    "meme rap": "#6d28d9",
    "lo-fi rap": "#6d28d9",
    "jazz rap": "#6d28d9",
    "abstract hip hop": "#7c3aed",
    "alternative hip hop": "#6d28d9",
    "deep underground hip hop": "#4c1d95",
    "canadian hip hop": "#6d28d9",
    "canadian old school hip hop": "#4c1d95",
    "australian hip hop": "#6d28d9",
    "bc underground hip hop": "#6d28d9",
    "asian american hip hop": "#7c3aed",
    "armenian hip hop": "#6d28d9",
    "christian hip hop": "#4c1d95",
    "desi hip hop": "#6d28d9",
    "gambian hip hop": "#6d28d9",
    "g funk": "#6d28d9",
    "glitch hop": "#6d28d9",
    "hawaiian hip hop": "#16a34a",
    "japanese old school hip hop": "#6d28d9",
    "josei rap": "#db2777",
    "k-rap": "#6d28d9",
    "latin hip hop": "#d97706",
    "lgbtq+ hip hop": "#ec4899",
    "pakistani hip hop": "#6d28d9",
    "pinoy hip hop": "#6d28d9",
    "punjabi hip hop": "#6d28d9",
    "russian drill": "#4c1d95",
    "russian drain": "#4c1d95",
    "trip hop": "#6d28d9",
    "uk hip hop": "#6d28d9",
    "uk alternative hip hop": "#6d28d9",
    "phonk brasileiro": "#b91c1c",
    "gym phonk": "#b91c1c",
    "aggressive phonk": "#b91c1c",
    "chill phonk": "#6d28d9",
    "anime phonk": "#9333ea",
    "drift phonk": "#0f766e",
    # Electronic / EDM
    "edm": "#7c3aed",
    "electronic": "#0891b2",
    "electronica": "#0891b2",
    "electro": "#0d9488",
    "electro house": "#0891b2",
    "electroclash": "#7c3aed",
    "electra": "#0891b2",
    "house": "#0891b2",
    "tech house": "#0d9488",
    "minimal tech house": "#0d9488",
    "disco house": "#0891b2",
    "chill house": "#0891b2",
    "filter house": "#0d9488",
    "g-house": "#0891b2",
    "stutter house": "#0891b2",
    "slap house": "#0891b2",
    "bass house": "#0891b2",
    "big room": "#0891b2",
    "chicago house": "#0891b2",
    "brazilian house": "#0891b2",
    "dutch house": "#0891b2",
    "di va house": "#db2777",
    "diva house": "#db2777",
    "nordic house": "#0891b2",
    "norwegian house": "#0891b2",
    "classic progressive house": "#0891b2",
    "future bass": "#0891b2",
    "melodic dubstep": "#0f766e",
    "cinematic dubstep": "#0f766e",
    "chillstep": "#0f766e",
    "atmospheric dnb": "#0f766e",
    "dancefloor dnb": "#0891b2",
    "liquid funk": "#0d9488",
    "complextro": "#0891b2",
    "cyberpunk": "#4c1d95",
    "dark clubbing": "#4c1d95",
    "alternative dance": "#0891b2",
    "indie electropop": "#0891b2",
    "indietronica": "#0891b2",
    "folktronica": "#78350f",
    "covertronica": "#0891b2",
    "aussietronica": "#0891b2",
    "chillwave": "#0891b2",
    "chillhop": "#d97706",
    "gaming edm": "#7c3aed",
    "belgian edm": "#0d9488",
    "dutch edm": "#0d9488",
    "pop edm": "#0d9488",
    "turkish edm": "#0891b2",
    "pakistani electronic": "#0891b2",
    "arab electronic": "#0891b2",
    "persian electronic": "#0891b2",
    "estonian electronic": "#0891b2",
    "canadian electronic": "#0891b2",
    "danish electronic": "#0891b2",
    "danish electropop": "#0d9488",
    "australian electropop": "#0891b2",
    "korean electropop": "#db2777",
    "swedish electropop": "#0891b2",
    "belgian dance": "#0891b2",
    "australian dance": "#0d9488",
    "german dance": "#0891b2",
    "bubblegum dance": "#f472b6",
    "nu disco": "#d97706",
    "disco": "#d97706",
    "new french touch": "#0891b2",
    "eurodance": "#1f6fca",
    "hi-nrg": "#0891b2",
    "hands up": "#0891b2",
    "hard bass": "#b91c1c",
    "freeform hardcore": "#b91c1c",
    "melbourne bounce international": "#0891b2",
    "vocal trance": "#0891b2",
    "wave": "#0891b2",
    "chiptune": "#16a34a",
    "pixel": "#16a34a",
    "video game music": "#16a34a",
    "speedrun": "#16a34a",
    "game mood": "#16a34a",
    "gaming edm": "#7c3aed",
    "glitch": "#4c1d95",
    "glitchcore": "#7c3aed",
    "weirdcore": "#7c3aed",
    "nightcore": "#7c3aed",
    "ethereal wave": "#7c3aed",
    "industrial pop": "#374151",
    "downtempo": "#64748b",
    "trip hop": "#6d28d9",
    "focus beats": "#0f766e",
    "abstract beats": "#7c3aed",
    "vapor twitch": "#a78bfa",
    # Lo-fi
    "lo-fi study": "#059669",
    "lo-fi chill": "#7c3aed",
    "lo-fi beats": "#a16207",
    "lo-fi brasileiro": "#a16207",
    "lo-fi cover": "#78350f",
    "lo-fi indie": "#a16207",
    "lo-fi jazzhop": "#b45309",
    "lo-fi latino": "#a16207",
    "lo-fi product": "#a16207",
    "lo-fi rap": "#6d28d9",
    "lo-fi sleep": "#64748b",
    "sad lo-fi": "#64748b",
    "anime lo-fi": "#db2777",
    "ambient lo-fi": "#0f766e",
    "christian lo-fi": "#78350f",
    "indian lo-fi": "#a16207",
    "indonesian lo-fi pop": "#a16207",
    "japanese chillhop": "#a16207",
    "slowed and reverb": "#64748b",
    # Indie / Folk / Singer-songwriter
    "indie folk": "#92400e",
    "indie soul": "#b45309",
    "indie r&b": "#0d9488",
    "indiecoustica": "#92400e",
    "indie viet": "#d97706",
    "indie poptimism": "#7c3aed",
    "indie game soundtrack": "#16a34a",
    "modern indie folk": "#92400e",
    "modern folk rock": "#92400e",
    "folk-pop": "#92400e",
    "ambient folk": "#4d7c0f",
    "indie anthem-folk": "#92400e",
    "children's folk": "#15803d",
    "native american": "#92400e",
    "stomp and holler": "#92400e",
    "new england americana": "#92400e",
    "alternative americana": "#92400e",
    "black americana": "#92400e",
    "austin rock": "#dc2626",
    "austindie": "#d97706",
    "pov: indie": "#d97706",
    "gen z singer-songwriter": "#b45309",
    "australian singer-songwriter": "#b45309",
    "british singer-songwriter": "#b45309",
    "canadian singer-songwriter": "#b45309",
    "irish singer-songwriter": "#15803d",
    "nashville singer-songwriter": "#b45309",
    "singaporean singer-songwriter": "#b45309",
    "swedish singer-songwriter": "#b45309",
    "nashville indie": "#d97706",
    "manchester indie": "#d97706",
    "birmingham indie": "#d97706",
    "leeds indie": "#d97706",
    "brighton indie": "#d97706",
    "oxford indie": "#d97706",
    "la indie": "#d97706",
    "brooklyn indie": "#d97706",
    "toronto indie": "#d97706",
    "minneapolis indie": "#d97706",
    "cleveland indie": "#d97706",
    "cincinnati indie": "#d97706",
    "detroit indie": "#d97706",
    "virginia indie": "#d97706",
    "new jersey indie": "#d97706",
    "ohio hip hop": "#6d28d9",
    "ann arbor indie": "#d97706",
    "tempe indie": "#d97706",
    "austindie": "#d97706",
    "icelandic indie": "#0f766e",
    "australian indie": "#d97706",
    "australian psych": "#7c3aed",
    "belgian indie": "#d97706",
    "belgian rock": "#dc2626",
    "dutch indie": "#d97706",
    "swiss indie": "#d97706",
    "alabama indie": "#d97706",
    "alaska indie": "#0f766e",
    "manitoba indie": "#d97706",
    "newfoundland indie": "#d97706",
    "bc underground hip hop": "#6d28d9",
    "chennai indie": "#d97706",
    "indian indie": "#b45309",
    "hindi indie": "#b45309",
    "indonesian r&b": "#0d9488",
    "belgian pop": "#1f6fca",
    "chamber psych": "#7c3aed",
    "shimmer psych": "#7c3aed",
    "french psychedelic": "#7c3aed",
    "french shoegaze": "#7c3aed",
    # Classical / Orchestral / Instrumental
    "classical": "#1d4ed8",
    "classical performance": "#1e3a8a",
    "baroque": "#1e3a8a",
    "american modern classical": "#1e3a8a",
    "american orchestra": "#1e40af",
    "british modern classical": "#1e3a8a",
    "british orchestra": "#1e40af",
    "hungarian classical performance": "#1e3a8a",
    "chinese classical performance": "#1e3a8a",
    "german soundtrack": "#1e3a8a",
    "british soundtrack": "#1e3a8a",
    "orchestral soundtrack": "#1e3a8a",
    "scorecore": "#1e3a8a",
    "epicore": "#1e3a8a",
    "instrumental post-rock": "#64748b",
    "instrumental math rock": "#d97706",
    "instrumental grime": "#4c1d95",
    "calming instrumental": "#0f766e",
    "compositional ambient": "#64748b",
    "italian library music": "#1e3a8a",
    "japanese piano": "#1e3a8a",
    "anime piano": "#c026d3",
    "anime score": "#7c3aed",
    "erhu": "#b45309",
    "fingerstyle": "#15803d",
    "guitar case": "#15803d",
    "ambient guitar": "#15803d",
    "j-ambient": "#0f766e",
    "j-acoustic": "#0f766e",
    "hollywood": "#e11d48",
    "broadway": "#e11d48",
    "show tunes": "#e11d48",
    "soundtrack": "#1e3a8a",
    "ballet class": "#e11d48",
    "sleep": "#64748b",
    "solipsynthm": "#64748b",
    "escape room": "#64748b",
    "pixel": "#16a34a",
    "video game music": "#16a34a",
    "indie game soundtrack": "#16a34a",
    "japanese vgm": "#16a34a",
    # J-pop / K-pop / Asian
    "j-pop": "#e11d48",
    "j-pop boy group": "#e11d48",
    "j-pop girl group": "#db2777",
    "j-idol": "#e11d48",
    "japanese alternative pop": "#db2777",
    "japanese dance pop": "#e11d48",
    "japanese teen pop": "#e11d48",
    "japanese alternative rock": "#dc2626",
    "japanese dub": "#0f766e",
    "denpa-kei": "#ec4899",
    "anime": "#7c3aed",
    "anime latino": "#e11d48",
    "anime rock": "#dc2626",
    "otacore": "#e11d48",
    "k-pop": "#db2777",
    "k-pop girl group": "#ec4899",
    "korean pop": "#db2777",
    "korean r&b": "#0d9488",
    "mandopop": "#e11d48",
    "cantopop": "#e11d48",
    "city pop": "#0891b2",
    "classic bollywood": "#b45309",
    "modern bollywood": "#b45309",
    "filmi": "#0891b2",
    # R&B / Soul / Funk
    "r&b": "#0d9488",
    "contemporary r&b": "#0d9488",
    "alternative r&b": "#0d9488",
    "chill r&b": "#0d9488",
    "dark r&b": "#4c1d95",
    "uk contemporary r&b": "#0d9488",
    "canadian contemporary r&b": "#0d9488",
    "australian r&b": "#0d9488",
    "bedroom r&b": "#0d9488",
    "bedroom soul": "#b45309",
    "indie r&b": "#0d9488",
    "indonesian r&b": "#0d9488",
    "korean r&b": "#0d9488",
    "neo soul": "#b45309",
    "classic soul": "#b45309",
    "british soul": "#b45309",
    "soul jazz": "#b45309",
    "indie soul": "#b45309",
    "pop soul": "#b45309",
    "funk": "#d97706",
    "funk carioca": "#d97706",
    "g funk": "#6d28d9",
    "nu disco": "#d97706",
    "disco": "#d97706",
    "adult standards": "#1e40af",
    "easy listening": "#64748b",
    "lilith": "#7c3aed",
    # Country / Folk
    "country": "#92400e",
    "contemporary country": "#92400e",
    "classic country pop": "#92400e",
    "classic texas country": "#92400e",
    "arkansas country": "#92400e",
    "alternative americana": "#92400e",
    # Latin
    "latin pop": "#e11d48",
    "latin hip hop": "#d97706",
    "reggaeton": "#d97706",
    "cumbia": "#d97706",
    "nuevo folklore mexicano": "#d97706",
    "colombian pop": "#1f6fca",
    "anime latino": "#e11d48",
    "canadian latin": "#d97706",
    "lo-fi latino": "#a16207",
    "chill baile": "#0d9488",
    "musica indigena latinoamericana": "#d97706",
    "musica portuguesa contemporanea": "#1f6fca",
    "pop quebecois": "#1f6fca",
    "funk carioca": "#d97706",
    "phonk brasileiro": "#b91c1c",
    "lo-fi brasileiro": "#a16207",
    "brazilian bass": "#16a34a",
    "brazilian edm": "#0d9488",
    "brazilian house": "#0891b2",
    "bossbeat": "#0d9488",
    "chanson": "#b45309",
    # Gospel / Religious
    "ccm": "#1e40af",
    "cedm": "#0891b2",
    "anthem worship": "#1e40af",
    "ambient worship": "#1e40af",
    "gregorian dance": "#1e40af",
    "hare krishna": "#d97706",
    "bhajan": "#92400e",
    "odia bhajan": "#b45309",
    # World / Regional
    "bhangra": "#d97706",
    "classic bhangra": "#d97706",
    "punjabi pop": "#d97706",
    "punjabi hip hop": "#6d28d9",
    "desi pop": "#b45309",
    "desi hip hop": "#6d28d9",
    "classic pakistani pop": "#b45309",
    "afrobeats": "#d97706",
    "afrofuturism": "#7c3aed",
    "reggae fusion": "#16a34a",
    "cumbia": "#d97706",
    "shanty": "#15803d",
    "hawaiian": "#16a34a",
    "acoustic opm": "#a16207",
    "pinoy hip hop": "#6d28d9",
    "nz hip hop": "#6d28d9",
    "chutney": "#d97706",
    "blues": "#1e40af",
    "abstract": "#6d28d9",
    "meme": "#d97706",
    "comic": "#d97706",
    "hopebeat": "#15803d",
    "deep tropical house": "#0d9488",
    "slowed and reverb": "#64748b",
    "wonky": "#64748b",
}
DEFAULT_COLOR = "#64748b"

AVAILABLE_GENRES = sorted([
    "a cappella", "abstract", "abstract beats", "abstract hip hop", "acoustic opm",
    "acoustic pop", "adult standards", "aesthetic rap", "afghan pop", "afrobeats",
    "afrofuturism", "aggressive phonk", "alabama indie", "alabama rap", "alaska indie",
    "album rock", "alt z", "alternative americana", "alternative dance", "alternative hip hop",
    "alternative metal", "alternative pop rock", "alternative r&b", "alternative rock",
    "ambient folk", "ambient guitar", "ambient lo-fi", "ambient pop", "ambient worship",
    "american modern classical", "american orchestra", "anime", "anime latino", "anime lo-fi",
    "anime phonk", "anime piano", "anime rock", "anime score", "ann arbor indie",
    "anthem worship", "antiviral pop", "arab electronic", "arab trap", "argentine ambient",
    "arkansas country", "armenian hip hop", "art pop", "asian american hip hop",
    "assamese pop", "atl hip hop", "atmospheric dnb", "aussietronica", "austin rock",
    "austindie", "australian alternative pop", "australian dance", "australian electropop",
    "australian hip hop", "australian indie", "australian pop", "australian psych",
    "australian r&b", "australian rock", "australian singer-songwriter", "ballet class",
    "barbadian pop", "baroque", "baroque pop", "bass house", "bass trap",
    "bc underground hip hop", "bedroom pop", "bedroom r&b", "bedroom soul", "belgian dance",
    "belgian edm", "belgian indie", "belgian pop", "belgian rock", "bhajan", "bhangra",
    "bhojpuri pop", "big room", "black americana", "blues", "blues rock", "bossbeat",
    "bow pop", "boy band", "boy pop", "brazilian bass", "brazilian edm", "brazilian house",
    "brighton indie", "britcore", "british alternative rock", "british indie rock",
    "british modern classical", "british orchestra", "british singer-songwriter",
    "british soul", "british soundtrack", "broadway", "brooklyn drill", "brooklyn indie",
    "brostep", "bubblegum dance", "cali rap", "calming instrumental", "canadian celtic",
    "canadian contemporary r&b", "canadian electronic", "canadian hip hop", "canadian latin",
    "canadian old school hip hop", "canadian pop", "canadian singer-songwriter", "candy pop",
    "cantopop", "ccm", "cedm", "celtic rock", "chamber pop", "chamber psych",
    "channel pop", "chanson", "chennai indie", "chicago house", "chicago indie",
    "chicago rap", "children's folk", "chill baile", "chill house", "chill out",
    "chill phonk", "chill pop", "chill r&b", "chillhop", "chillstep", "chillwave",
    "chinese classical performance", "chinese electropop", "chinese idol pop",
    "chinese viral pop", "chiptune", "christian alternative rock", "christian hip hop",
    "christian lo-fi", "christian rock", "chutney", "cincinnati indie", "cinematic dubstep",
    "city pop", "classic bhangra", "classic bollywood", "classic country pop",
    "classic pakistani pop", "classic progressive house", "classic rock", "classic soul",
    "classic swedish pop", "classic texas country", "classic uk pop", "classical",
    "classical performance", "cleveland indie", "cloud rap", "colombian pop", "comic",
    "complextro", "compositional ambient", "conscious hip hop", "contemporary country",
    "contemporary r&b", "country", "covertronica", "cumbia", "cyberpunk", "dance pop",
    "dance rock", "dancefloor dnb", "danish electronic", "danish electropop", "danish pop",
    "dark clubbing", "dark plugg", "dark pop", "dark r&b", "dark trap", "death metal",
    "deep tropical house", "deep underground hip hop", "denpa-kei", "desi hip hop",
    "desi pop", "detroit hip hop", "detroit indie", "dfw rap", "disco", "disco house",
    "diva house", "dmv rap", "downtempo", "dreamo", "drift phonk", "dutch edm",
    "dutch house", "dutch indie", "dutch pop", "east coast hip hop", "easy listening",
    "edm", "electra", "electro", "electro house", "electro-pop francais", "electroclash",
    "electronica", "electropop", "emo", "emo rap", "english indie rock", "epicore",
    "erhu", "escape room", "estonian electronic", "ethereal wave", "eurobeat",
    "eurodance", "europop", "experimental pop", "filmi", "filter house", "fingerstyle",
    "finnish alternative rock", "florida drill", "focus beats", "folk-pop", "folktronica",
    "freeform hardcore", "french hip hop", "french indie pop", "french pop",
    "french psychedelic", "french shoegaze", "funk", "funk carioca", "funk metal",
    "future bass", "future rock", "g funk", "g-house", "gambian hip hop", "game mood",
    "gaming edm", "gangster rap", "garage rock", "garage rock revival", "gauze pop",
    "gen z singer-songwriter", "german dance", "german pop", "german pop rock",
    "german soundtrack", "girl group", "glam metal", "glam rock", "glitch", "glitch hop",
    "glitchcore", "gregorian dance", "grunge", "guitar case", "gujarati pop", "gym phonk",
    "hands up", "hard bass", "hard rock", "hare krishna", "hawaiian", "hawaiian hip hop",
    "hi-nrg", "himachali pop", "hindi indie", "hip hop", "hip pop", "hmong pop",
    "hollywood", "hopebeat", "house", "hungarian classical performance", "hyperpop",
    "hypnagogic pop", "icelandic indie", "indian indie", "indian lo-fi", "indie anthem-folk",
    "indie electropop", "indie emo", "indie folk", "indie game soundtrack", "indie garage rock",
    "indie pop", "indie pop rap", "indie poptimism", "indie r&b", "indie rock",
    "indie rock italiano", "indie rockism", "indie soul", "indie viet", "indiecoustica",
    "indietronica", "indonesian lo-fi pop", "indonesian r&b", "indonesian singer-songwriter",
    "industrial pop", "instrumental grime", "instrumental math rock", "instrumental post-rock",
    "irish pop", "irish rock", "irish singer-songwriter", "israeli mediterranean",
    "israeli pop", "italian indie pop", "italian library music", "j-acoustic", "j-ambient",
    "j-idol", "j-pop", "j-pop boy group", "j-pop girl group", "j-poprock", "j-rock",
    "japanese alternative pop", "japanese alternative rock", "japanese chillhop",
    "japanese dance pop", "japanese dub", "japanese old school hip hop", "japanese piano",
    "japanese teen pop", "japanese vgm", "jazz cover", "jazz rap", "josei rap", "k-pop",
    "k-pop girl group", "k-rap", "kazakh pop", "korean electropop", "korean pop",
    "korean r&b", "la indie", "la pop", "latin hip hop", "latin pop", "leeds indie",
    "lgbtq+ hip hop", "lilith", "liquid funk", "lithuanian electronic", "lo-fi beats",
    "lo-fi brasileiro", "lo-fi chill", "lo-fi cover", "lo-fi indie", "lo-fi jazzhop",
    "lo-fi latino", "lo-fi product", "lo-fi rap", "lo-fi sleep", "lo-fi study",
    "malaysian pop", "mandopop", "manitoba indie", "melbourne bounce international",
    "melodic drill", "melodic dubstep", "melodic metalcore", "melodic rap", "melodipop",
    "meme", "meme rap", "memphis hip hop", "metallic hardcore", "metropopolis",
    "minimal tech house", "minneapolis indie", "modern alternative pop", "modern alternative rock",
    "modern bollywood", "modern dream pop", "modern folk rock", "modern indie folk",
    "modern indie pop", "modern rock", "musica indigena latinoamericana",
    "musica portuguesa contemporanea", "nashville indie", "nashville singer-songwriter",
    "native american", "neo mellow", "neo soul", "neon pop punk", "new england americana",
    "new french touch", "new jersey indie", "new romantic", "new wave pop", "newfoundland indie",
    "nightcore", "nightrun", "noise pop", "nordic house", "norwegian house", "norwegian pop",
    "nu disco", "nuevo folklore mexicano", "nyc pop", "nyc rap", "nz hip hop", "nz pop",
    "odia bhajan", "odia pop", "ohio hip hop", "orchestral soundtrack", "otacore",
    "oxford indie", "pakistani electronic", "pakistani hip hop", "pakistani pop",
    "permanent wave", "persian electronic", "persian pop", "phonk brasileiro", "piano rock",
    "pinoy hip hop", "pittsburgh rap", "pixel", "plugg", "pluggnb", "pop", "pop dance",
    "pop edm", "pop folk", "pop quebecois", "pop r&b", "pop rap", "pop soul",
    "post-grunge", "post-teen pop", "pov: indie", "punjabi hip hop", "punjabi pop",
    "r&b", "rage rap", "rap rock", "reggae fusion", "reggaeton", "romanian pop",
    "russian drain", "russian drill", "russian pop", "sad lo-fi", "sad rap", "scandipop",
    "scorecore", "scottish indie", "shanty", "shimmer pop", "shimmer psych", "show tunes",
    "singaporean pop", "singaporean singer-songwriter", "singer-songwriter pop", "slap house",
    "sleaze rock", "sleep", "slowed and reverb", "social media pop", "solipsynthm",
    "soul jazz", "soundtrack", "south african pop", "sped up", "speedrun",
    "stomp and holler", "stutter house", "super eurobeat", "swedish electropop",
    "swedish pop", "swedish singer-songwriter", "swiss indie", "swiss pop", "tech house",
    "teen pop", "telugu indie", "tempe indie", "thai indie rock", "toronto indie",
    "trap", "trap queen", "traprun", "trip hop", "turkish edm", "uk alternative hip hop",
    "uk contemporary r&b", "uk dance", "uk hip hop", "uk pop", "ukrainian viral pop",
    "vapor pop", "vapor twitch", "video game music", "viral pop", "viral rap",
    "virginia indie", "vocal trance", "wave", "weirdcore", "wonky",
])

AUDIO_FEATURES = [
    {
        "key": "pref_danceability",
        "label": "Danceability",
        "desc": "How suitable for dancing (rhythm, beat stability)",
    },
    {
        "key": "pref_energy",
        "label": "Energy",
        "desc": "Intensity and activity - loud fast tracks score high",
    },
    {
        "key": "pref_valence",
        "label": "Mood (Valence)",
        "desc": "Positivity - high = happy/euphoric, low = sad/tense",
    },
    {
        "key": "pref_acousticness",
        "label": "Acousticness",
        "desc": "Confidence the track is acoustic (no electronics)",
    },
    {
        "key": "pref_instrumentalness",
        "label": "Instrumentalness",
        "desc": "Likelihood of no vocals - close to 1 = purely instrumental",
    },
]


def _spotify_track_url(row):
    track_id = (row.get("id") or "").strip()
    if track_id:
        return f"https://open.spotify.com/track/{track_id}"

    uri = (row.get("uri") or "").strip()
    if uri.startswith("spotify:track:"):
        return f"https://open.spotify.com/track/{uri.split(':')[-1]}"

    return (row.get("track_href") or "").strip()


def _load_csv():
    songs = []
    try:
        with open(CSV_PATH, encoding="utf-8") as f:
            for row in csv.DictReader(f):
                try:
                    songs.append(
                        {
                            "trackName": row["trackName"],
                            "artistName": row["artistName"],
                            "genre": row.get("genre", "").strip(),
                            "danceability": float(row["danceability"] or 0),
                            "energy": float(row["energy"] or 0),
                            "valence": float(row["valence"] or 0),
                            "tempo": float(row["tempo"] or 0),
                            "acousticness": float(row["acousticness"] or 0),
                            "instrumentalness": float(row["instrumentalness"] or 0),
                            "loudness": float(row.get("loudness") or 0),
                            "speechiness": float(row.get("speechiness") or 0),
                            "liveness": float(row.get("liveness") or 0),
                            "ms_played": float(row.get("msPlayed") or 0),
                            "duration_ms": int(float(row.get("duration_ms") or row.get("msPlayed") or 0)),
                            "spotify_url": _spotify_track_url(row),
                        }
                    )
                except (ValueError, KeyError):
                    continue
    except FileNotFoundError:
        pass
    return songs


ALL_SONGS = _load_csv()


def get_saved_genres(prefs):
    return json.loads(prefs.genres) if prefs and prefs.genres else []



